config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'times/index'
  root "goals#index"
  namespace :users do
    resources :rankings, only: [:index,:show]
  end
  resources :goals, except: [:destroy]
  resources :y_times, except: [:new,:destroy]
  resources :users, except: [:create,:destroy]
  resources :authors, only: [:new,:create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/goal.rb
class Goal < ApplicationRecord
  validates :name, presence: true
  validates :time, presence: true
  validates :image, presence: true

  has_many :y_times
  has_many :users
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #belongs_to :goal
  has_many :y_times
end

app/models/y_time.rb
class YTime < ApplicationRecord
  validates :time, presence: true
  belongs_to :goal
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :exception


  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def new
    @author = Author.new()
    @comments = Author.all

    #binding.pry
  end

  def create
    Author.create(comments_params)
    redirect_to new_author_path
  end

  def comments_params
    params.require(:author).permit(:comments, :name)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def index
    if user_signed_in?
    if current_user.goal_id != nil && current_user.email !="testtest@test"
      redirect_to user_path(current_user.id)
    end
    end
  end

  def show 
    @user = User.find(current_user.id)
    @goal = Goal.new()

    #挑戦者が多い順に並べ替え########################################################
    goals = Goal.all.includes(:users)
    goals_list = []
    goals.each do |goal|
      goals_list << goal
    end
    @goals_ordered_list = goals_list.sort_by {|goal| goal.users.count }.reverse
    #############################################################################
  end

  def new
    @goal = Goal.new()
  end

  def create
    Goal.create(goal_params)
    redirect_to goal_path(current_user.id)
  end

  def edit
    
  end

  def update

  end

  
  private
  def goal_params
    params.require(:goal).permit(:name, :time, :image)
  end
end

app/controllers/users/rankings_controller.rb
class Users::RankingsController < ApplicationController
  def index
    @user = User.find(current_user.id)
    @goal = Goal.find(current_user.goal_id)
    #@same_goal_users = Goal.find(current_user.goal_id).users

    # @same_goal_users = Goal.find(current_user.goal_id).y_times.joins(:user).group(:user_id).sum(:time)

    @same_goal_users = Goal.find(current_user.goal_id).y_times.joins(:user).group(:user).sum(:time).sort {|(k1, v1), (k2, v2)| v2 <=> v1 }
    #binding.pry
  end

  def show
    @user = User.find(current_user.id)
    @goal = Goal.find(current_user.goal_id)
    @all_users = YTime.all.joins(:user).group(:user).sum(:time).sort {|(k1, v1), (k2, v2)| v2 <=> v1 }

    #path = request.path
    #binding.pry
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    #binding.pry
      user = User.find(current_user.id)

    # if user_params[:goal_id] == nil 
    #   redirect_to goal_path(current_user.id)
    # end

    user.update(user_params)
    #binding.pry
    if user_params[:week_time] == "" || user_params[:week_time] == nil || user_params[:goal_id] != nil
      redirect_to edit_y_time_path
    else
      redirect_to y_times_path
    end
  end

  def show
    #挨拶、時間ごとに変化
    @nowTime = DateTime.now.hour  #挨拶表示のため、現在時刻を取得
    @greeting = "調子はどうですか？"
    if @nowTime >= 4 && @nowTime < 10
      @greeting = "おはようございます!!"
    elsif @nowTime >= 10 && @nowTime < 18
      @greeting = "こんにちは!!"
    elsif @nowTime >= 18 && @nowTime < 23 || @nowTime >= 0
      @greeting = "こんばんわ!!"
    end
    #挨拶ここまで


    @user = User.find(params[:id])
    @goal = Goal.find(current_user.goal_id)
    @date = (Date.current - @user.created_at.to_date + 1).numerator #何日め表記なので現在日-登録日+1
    
    @total_time = @user.y_times.sum(:time)
    @progress_rate = 100*(@user.y_times.sum(:time) / @goal.time).round(5) #進捗率、小数点5桁まで表示すれば数値が変化しないということはないという考え
    #binding.pry

    #メッセージ、進捗率ごとに変化
    @progress_message = ""
    if @progress_rate >= 0 && @progress_rate < 10
      @progress_message = "スタートダッシュ!!"
    elsif @progress_rate >= 10 && @progress_rate < 50
      @progress_message ="少しづつ目標が見えてきましたか？"
    elsif @progress_rate >= 50 && @progress_rate < 100
      @progress_message ="そろそろなりたい姿に近づいてきたのではないでしょうか?"
    elsif @progress_rate > 100
      @progress_message ="なりたい自分になれたでしょうか？  まだまださらなる高みを目指しましょう"
    end
    #メッセージここまで


    @y_time = YTime.new() #積み上げ時間入力フォーム用

    @data = User.find(params[:id]).y_times.pluck(:created_at, :time) #積み上げ時間取得


    #統計データここから################################################################
    #入力日ごとのスタック時間
    @daily_total_data = [[@user.created_at.strftime('%m/%d'),0.0]]
      for i in 0..@data.length-1 do
        if i == 0
          @daily_total_data << [@data[0][0].strftime('%m/%d'),@data[0][1]]
        else
          @daily_total_data << [@data[i][0].strftime('%m/%d'),@daily_total_data.last[1] + @data[i][1]]
        end
      end

    #入力日ごとのスタック進捗率
    @daily_progress_data = []
      for i in 0..@daily_total_data.length-1 do
        @daily_progress_data << [@daily_total_data[i][0], ((@daily_total_data[i][1]) / (@goal.time) * 100).round(5) ]
      end
  
    #曜日毎のスタック時間
    @sca_data = [[@user.created_at.strftime('%w'),0.0]]
      for i in 0..@data.length-1 do
        if i == 0
          @sca_data << [@data[0][0].strftime('%w'),@data[0][1]]
        else
          @sca_data << [@data[i][0].strftime('%w'),@sca_data.last[1] + @data[i][1]]
        end
      end
    #入力日毎（日毎に合計値を算出）の時間
    if @data.length > 0
    @pie_data = [[@data[0][0].strftime('%m/%d'),@data[0][1]]]
      for i in 1..@data.length-1 do
        if @pie_data.last[0] == @data[i][0].strftime('%m/%d')
          @pie_data[@pie_data.size-1] = [@pie_data.last[0] , @pie_data.last[1] + @data[i][1] ]
        else
          @pie_data << [@data[i][0].strftime('%m/%d'), @data[i][1]]
        end
      end
    end

    #入力日毎（日毎に合計値を算出）の時間
    @column_data = @pie_data
    #統計データここまで################################################################
  end

  def new
    
  end

  private
  def user_params
    params.require(:user).permit(:name, :email,:week_time,:image,:public_flag,:goal_id)
  end
end

app/controllers/y_times_controller.rb
class YTimesController < ApplicationController

  def index
    @user = User.find(current_user.id)        #ユーザー情報
    @goal = Goal.find(current_user.goal_id)   #ユーザーのgoal_idをみて目標を出力
    
    @required_week = (@goal.time / @user.week_time)
    @required_month = (@required_week / 4)

    @achievement_date = (Date.current + (7 * @required_week)).strftime("%Y年%-m月%-d日")
    # @date = (Date.current - @user.created_at.to_date + 1).numerator 
    #binding.pry
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update

  end

  def show
    
  end

  def create
    y_time = YTime.create(y_time_params)
    redirect_to user_path(current_user.id)
  end

  private

  def y_time_params
    params.require(:y_time).permit(:time,:note).merge(user_id: current_user.id, goal_id: current_user.goal_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/times_helper.rb
module TimesHelper
end

app/helpers/users/rankings_helper.rb
module Users::RankingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/y_times_helper.rb
module YTimesHelper
end

app/views/authors/new.html.erb
<%= render partial: "template/page_top",  locals: {guide_message: "作者自己紹介（仮設）"}%>



<section id="self_introduce">
<div class= "twitter">
<a href= "https://twitter.com/sako205022118">
<h3>sakozo</h3><%= image_tag  "https://pbs.twimg.com/profile_images/1203685921205276674/WnHv8LhL_400x400.jpg", class: "photo" %><br>
Twitterアカウントに飛びます</a><br>
</div>
<br>

<p>昨年大学院修士課程を修了、社会人１年目</p>
<p>カビ菌を使って細胞分裂の研究をしていました。</p>
<p>論文を２本出しました、もし興味がありましたら↓</p>
<a href= "https://www.ncbi.nlm.nih.gov/pubmed/30463883">https://www.ncbi.nlm.nih.gov/pubmed/30463883</a><br>
<a href= "https://www.ncbi.nlm.nih.gov/pubmed/29167352">https://www.ncbi.nlm.nih.gov/pubmed/29167352</a>


<div class="input_area">
コメント、感想などありましたら
<%= form_for @author do |form| %>
  <div><%= form.text_area :comments , class: "comment_form", size: "86x2" %></div>
  <%= form.submit "送信", class: "submit_button" %>
<% end %>
</div>

<div class="comment_area">
<% @comments.each do |comment| %>
<div><%= comment.comments %></div>
<% end %>
</div>


</section>

<%= stylesheet_link_tag "book/personal_page", :media => "all" %>

app/views/goals/index.html.erb
<%= image_tag  "toppagecandidate.jpg", class: "bg_image"%>
<%= stylesheet_link_tag "book/top_page", :media => "all" %>
<section id="top_page">
<h1>You will be...?</h1>
<%
=begin%>
 <div class="user">
    <p>By作者</p>
</div> 
<%
=end%>
<div class="message">
<p>あなたがなりたい姿はありますか?</p>
<p>実は、思っているよりも早くなれるかもしれません…</p>
</div>

<br>


<% if user_signed_in? %>
  <div class="control">
  <%= link_to "はじめる" , goal_path(current_user.id), class: "button" %>
  </div>
<% else %>  
  <div class="control">
  <%= link_to "ログイン・ユーザー登録" , new_user_session_path, class: "login_button" %>
  </div>
  <div class="test_login_label">
    <%= form_for(User.new, url:"/users/sign_in") do |f|  %>
    <%= f.hidden_field :name, value: "test" %>
    <%= f.hidden_field :email, value: "testtest@test" %>
    <%= f.hidden_field :password, value: "111111" %>
    <%= f.submit "テストユーザーでかんたんログイン", class: "test_login_button"%> 
  <% end %>
  </div>
</div>
<% end %>
</section >

app/views/goals/new.html.erb
<a href=http://localhost:3000><h1>You will be</h1></a>
<p>あなたがなりたいものを教えてください</p>


<%= form_for @goal do |form| %>
  <%= form.text_field :name, placeholder: "なりたいもの" %>
  <%= form.text_field :time, placeholder: "かかる時間" %>
  <%= form.text_field :image, placeholder: "イメージ画像" %>
  <%= form.submit "SEND" %>
<% end %>
<br>

app/views/goals/show.html.erb
<link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
 <%= render partial: "template/page_top",  locals: {guide_message: "あなたがなりたい姿を教えてください"}%>
<%= stylesheet_link_tag "book/select_goal", :media => "all" %>
<%= form_for @user do |f| %>

<div class="message">
<p class="">一覧になければ自分で作ることもできます</p>
<button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#post">自分で設定する</button>
</div>

<div class="contents">
<ul class="horizontal-list">
  <% @goals_ordered_list.each do |goal| %>
      <li class="choices">

        <% if goal.id == 1 %>
          <label>
          <div class="text">
          <p><%= f.radio_button :goal_id, goal.id, checked: true %><%=goal.name%> <br><%=goal.time%>時間 <br>挑戦中:<%=goal.users.count%>人 <br><%= image_tag goal.image, :size =>'200x200' %>
          </p>
          </div>
          </label>

        <% else %>
          <label>
          <div class="text">
          <p><%= f.radio_button :goal_id, goal.id %><%=goal.name%> <br><%=goal.time%>時間 <br>挑戦中:<%=goal.users.count%>人 <br><%= image_tag goal.image, :size =>'200x200' %>
          </p>
          </div>
          </label>
        <% end %>
      </li>
  <% end %>
    
</ul>
</div>



<br>
<div class="submit_button">
<%= f.submit "決定!!", class: "button" %>
</div>
<% end %>
</div>
<br><br>



<div class="container text-center">
  <div class="modal fade" id="post" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <%= form_for @goal do |form| %>
      <div class="modal-content">
        <div class="modal-body">

            <div class="create_goal">
              <%= form.text_field :name, placeholder: "なりたいもの" ,class: "input_form" %>
              <%= form.text_field :time, placeholder: "かかる時間" ,class: "input_form" %>
              <label>
              <i class="fa fa-file-image"></i>
              <%= form.file_field :image, class: "image", id: "file", style: "display:none;"%>
              </label>
            </div>

        </div>
        <div class="modal-footer">
          <%= form.submit "作成!", class: "btn btn-primary"%>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
        </div>
      </div>
      <% end %>
    </div>
  </div>

</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>You will be...?</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/template/_login_page_top.html.erb
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.bundle.min.js" integrity="sha384-pjaaA8dDz/5BgdFUPX6M/9SUZv4d12SUPF0axWc+VRZkx5xU3daN+lYb49+Ax+Tl" crossorigin="anonymous"></script>
<%= stylesheet_link_tag "book/page_top", :media => "all" %>
<div class="title_area">
  <div class="title_area__title">
    <h1>You will be...?</h1>
  </div>

</div>
<div class="menubar">
  <p class="guide_message"><%= guide_message %></p>
</div>

app/views/template/_page_top.html.erb
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.bundle.min.js" integrity="sha384-pjaaA8dDz/5BgdFUPX6M/9SUZv4d12SUPF0axWc+VRZkx5xU3daN+lYb49+Ax+Tl" crossorigin="anonymous"></script>
<%= stylesheet_link_tag "book/page_top", :media => "all" %>
<div class="title_area">
  <div class="title_area__title">
    <h1>You will be...?</h1>
  </div>

  <% if request.path.slice(0..6) == "/users/" && request.path.slice(7..14) != "rankings" %>
    <div class="title_area__ranking_button">
    <%= link_to "ランキングページへ", users_rankings_path , class: "btn btn-success" %>
    </div>
  <% elsif request.path.slice(0..15) == "/users/rankings" %>
    <div class="title_area__ranking_button">
    <%= link_to  "マイページへ", user_path(current_user.id) ,class: "btn btn-primary"%>
    </div>
    <div class="title_area__ranking_button">
    <%= link_to "全体ランキングへ", users_ranking_path(current_user.id) , class: "btn btn-danger" %>
    </div>
  <% elsif request.path.slice(0..15) == "/users/rankings/" || request.path.slice(0..12) == "/authors/new" %>
    <div class="title_area__ranking_button">
    <%= link_to  "マイページへ", user_path(current_user.id) ,class: "btn btn-primary" %>
    </div>
    <div class="title_area__ranking_button">
    <%= link_to "ランキングページへ", users_rankings_path , class: "btn btn-success" %>
  </div>
  <% end %>

  <div class="title_area__logout_button">
    <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-outline-secondary" %>
  </div>


</div>
<div class="menubar">
  <p class="guide_message"><%= guide_message %></p>
</div>

app/views/users/rankings/index.html.erb
 <%= render partial: "template/page_top",  locals: {guide_message: "積み上げ時間ランキング　#{@goal.name}を目指しているひとたち"}%>
<%= stylesheet_link_tag "book/ranking_page", :media => "all" %>

<div class="message">

</div>
<br>
<div class="ranking_area">
<% @same_goal_users.each.with_index(1) do |(user, total_time), index| %>
  <%= link_to user_path(user.id) ,class: "link" do %>
    <div class="ranking_panel">
    <%= index %>位  <%= user.name%>さん <%= total_time.round(1) %>時間  <br>
    </div>
  <% end %>
<% end %>
</div>

app/views/users/rankings/show.html.erb
 <%= render partial: "template/page_top",  locals: {guide_message: "積み上げ時間ランキング　このアプリを使って取り組んでくださっているひとたち"}%>


<div class="message">

</div>
<br>
  
<div class="ranking_area">
<% @all_users.each.with_index(1) do |(user, total_time), index| %>
  <%= link_to user_path(user.id) ,class: "link" do %>
    <div class="ranking_panel all_users">
    <%= index %>位  <%= user.name%>さん <%= total_time.round(1) %>時間<br>
    </div>
  <% end %>
<% end %>
</div>

<%= stylesheet_link_tag "book/ranking_page", :media => "all" %>

app/views/users/show.html.erb
<% if @user.id == current_user.id %>
<%= render partial: "template/page_top",  locals: {guide_message: "#{@user.name}さん#{@greeting}　#{@progress_message}"}%>
<% else %>
<%= render partial: "template/page_top",  locals: {guide_message: "#{@user.name}さんのマイページ"}%>
<% end %>

<div class="message">
<p>本日は<%= @goal.name %>になるためにとりくみ始めてから<strong><%= @date %>日目</strong>ですね　　<% if current_user.id == @user.id %><%= link_to "作成者の自己紹介ページへ", new_author_path, class: "self_introduce" %><% end %></p> 

</div>

<div class="contents">
<div class="left_content">
<!--最速で目標達成できる日付も書いておこう-->
<h2 class="progress_rate" >進捗率:  <%= @progress_rate.round(5) %>%</h2>

<% if @user.id == current_user.id %>
<div class="input_area">
<%= form_for @y_time do |form| %>
  <div class="input_time"><%= form.text_field :time, placeholder: "3.5", type: "number", min:"0" %>時間</div><br>
  <div><%= form.text_field :note, placeholder: "メモ(任意)",class: "input_memo" %></div><br>
  <div ><%= form.submit "記録する", class: "submit_button"%></div>
<% end %>
</div>   <!--バリデーションをあとで設定する--><!--間違えた時の削除機能も追加する-->
<% else %>
<div class="input_area">
<%= form_for @y_time do |form| %>
  <div class="input_time"><%= form.text_field :time, placeholder: "3.5", type: "number", min:"0" , readonly: true %>時間</div><br>
  <div><%= form.text_field :note, placeholder: "メモ(任意)",class: "input_memo" , readonly: true %></div><br>
  <div ><%= form.submit "記録する" ,class: "submit_button disabled_button",type: "disable", readonly: true %></div>
<% end %>
</div>
<% end %>

<div class="y_times">
<p class="total_time">Total: <%= @total_time.round(1) %>時間</p>
  <div class="y_times__scroll">
  <% @user.y_times.order(id: "DESC").each do |y_time| %>
    <%= y_time.time.round(1) %>時間  <%= y_time.created_at.strftime('%y/%m/%d') %> 
    <%if y_time.note.present? %>
      <%= ": #{y_time.note}" %>
    <% end %>
    <br>
  <% end %>
  </div>
</div>
<br>
</div> <!-- left_content ここまで -->


<div class ="right_content">

<div class='tabs'>
  <div class='tab-buttons'>
    <span class='content1'>進捗率</span>
    <span class='content2'>日ごと(棒)</span>
    <span class='content3'>日ごと(円)</span>
    <span class='content4'>曜日ごと</span>
    <span class='content5'>トータル</span>

    <div id='lamp' class='content1'></div>
  </div>
  <div class='tab-content'>
    
    <div class='content1'><h3>進捗率</h3>
<%= line_chart @daily_progress_data, width: "450px", height: "350px", suffix: "%" , colors: ["#DB077F", "#DB077F"]%></div>
    
    <div class='content2'><h3>入力日ごとの時間</h3>
<%= column_chart @column_data, discrete: true, width: "450px", height: "350px", suffix: "h" , colors: ["#0065B2", "#0065B2"] %></div>
    
    <div class='content3'><h3>入力日ごとの時間（円グラフ）</h3>
<%= pie_chart @pie_data,width: "450px", height: "350px" , legend: false  , suffix: "h" %></div>

    <div class='content4'><h3>曜日ごとの積み上げ時間（0:Sun,1:Mon,2:Tue,3:Wed...）</h3>
<%= scatter_chart @sca_data,  width: "450px", height: "350px" , suffix: "h" , colors: ["#b00", "#666"] %></div>

    <div class='content5'><h3>これまでに積み上げた時間</h3>
<%= area_chart @daily_total_data,width: "450px", height: "350px", suffix: "h", curve: false  %></div>
  </div>
</div>
<div class='credit'>
</div> <!--right_content-->
</div> <!-- contents --> 
<%= stylesheet_link_tag "book/personal_page", :media => "all" %>
<%= javascript_include_tag 'book/personal_page.js' %>

app/views/y_times/edit.html.erb
<%= stylesheet_link_tag "book/input_y_time", :media => "all" %>
 <%= render partial: "template/page_top",  locals: {guide_message: "あなたの普段の生活を教えてください"}%>
<div class="message">
<p>もし目標に向けてフルコミットできた場合、何週間でなりたい姿になれるかを計算します。</p>
<p>週休２日を想定しています。他の時間は全てなりたい姿のための積み上げ時間として換算します。</p>
</div>

<div class="contents">

<section id = "week_time_form">

<div class="input_area">
  <p class="input_area__title" >1日の、、、</p>
  <div class="input_times">
    <div class="sleep_time">
    <p>睡眠時間</p><input type="number" min="0" class="input_form" v-model="time1" placeholder="7.5" >
    </div><br>
    <div class="work_time">
    <p>仕事・学校時間</p><input type="number" min="0" class="input_form"  v-model="time2" placeholder="8.5" >
    </div><br>
    <div class="home_time">
    <p>食事・仕度・家事時間</p><input type="number" min="0"  class="input_form" v-model="time3" placeholder="2">
    </div>
  </div>
</div>


<div class="results_area">
  <p class="results_area__title" >あなたの時間は、、、</p>
  <div class="both_parts">
    <div class="left_part">
      <div class="week_day_time"><p>{{week_day_time}}</p></div>
      <div class="week_end_time"><p>{{week_end_time}}</p></div>
    </div>
    <div class="right_part">
      <div class="week_time"><p>{{week_time}}</p></div>
    </div>
  </div>
</div>

<%= form_for @user do |form| %>
  <%= form.text_field :week_time, placeholder: "hidden", "v-model": "input_week_time", type: "hidden" %>
  <%= form.submit "結果を見る", class: "button" %>
<% end %>
</section>


<div class="button_area">

</div>
<%= javascript_pack_tag "week_time" %>

app/views/y_times/index.html.erb
<%= stylesheet_link_tag "book/cal_result", :media => "all" %>
<%= render partial: "template/page_top",  locals: {guide_message: "なりたい姿に向けて今からはじめてみませんか？"}%>
<div class="message">
<p class="message__date"><%= @user.name %>さん、あなたが1週間で<%=@user.week_time%>時間ずつ積み上げることができれば</p>
<p class="message__week"><%=@required_week.round%>週間（<%=@required_month.round(1)%>ヶ月）後の、</p>
<p class="message__week"><%= @achievement_date %>に<%=@goal.name%>になっているかもしれません</p>

</div>
<div class="control">
<%= link_to "はじめる" , user_path(current_user.id), class: "button" %>
</div>